GENIVI/CANdevStudio

CMakeLists.txt, cmake/Modules/CompilerVersion.cmake
https://at.projects.genivi.org/jira/browse/CDS-9
https://at.projects.genivi.org/jira/browse/CDS-8
=> Check compiler version and complain if version is to old

.gitmodules
Signed-off-by: Remigiusz Kołłątaj <remigiusz.kollataj@gmail.com>
=> Remove Catch as it is included in fakeit

src/components/CMakeLists.txt, src/components/canrawview/canrawview.cpp, src/components/canrawview/canrawview.h, src/components/canrawview/canrawview_p.h, src/gui/mainwindow.cpp
New PR
Signed-off-by: Michał Maćkowski <m_mackowski@yahoo.com>
=> CDS-32 CANrawViewer: Received frames shall table view with following columns

src/gui/mainwindow.cpp, src/gui/mainwindow.h, src/gui/mainwindow.ui
Signed-off-by: Michał Maćkowski <m_mackowski@yahoo.com>
=> CDS-17 CANdevStudio shall contain menu

src/components/canrawsender/canrawsender.ui
CANrawSender: It shall be possible to sort items in the table by each column in ascending and descending manner - functionality was added
=> CDS-43 sort funcionality add

src/components/canrawview/canrawview_p.h
clear button functionality add.
=> CDS-59 clear button implementation

src/components/canrawsender/canrawsender_p.h
=> CDS- 42 CanRawSender Reorganised feature add

src/components/candevice/candevice.cpp, src/components/candevice/candevice.h, src/components/candevice/candevice_p.h, src/gui/mainwindow.cpp
- Add default factory (factory impl must be passed only in UT)
- Fix factory lifetime issue
- Move factory to private class.
=> CanFactoryQt refactoring

src/components/canrawview/canrawview.ui, src/components/canrawview/canrawview_p.h
Sorting bug fix. Table will be now sorted after reception of each frame.
=> CDS-66 Sorting in CANrawView do not affect new data

src/components/CMakeLists.txt, src/components/canrawsender/canrawsender.cpp, src/components/canrawsender/canrawsender.h, src/components/canrawsender/canrawsender_p.h, src/components/canrawsender/canrawsendermodel.cpp, src/components/canrawsender/crsfactory.hpp, src/components/canrawsender/crsfactoryinterface.hpp, src/components/canrawsender/crsgui.hpp, src/components/canrawsender/crsguiinterface.hpp, src/components/canrawsender/newlinemanager.cpp, src/components/canrawsender/newlinemanager.h, src/components/canrawsender/nlmcheckbox.hpp, src/components/canrawsender/nlmcheckboxinterface.hpp, src/components/canrawsender/nlmfactory.hpp, src/components/canrawsender/nlmfactoryinterface.hpp, src/components/canrawsender/nlmlineedit.hpp, src/components/canrawsender/nlmlineeditinterface.hpp, src/components/canrawsender/nlmpushbutton.hpp, src/components/canrawsender/nlmpushbuttoninterface.hpp, src/gui/mainwindow.cpp, src/gui/mainwindow.h, tests/CMakeLists.txt, tests/newlinemanager_test.cpp
Added new class - new line manager-  for showing clearly relation between cells and get easy way to adds new row.
=> CDS-40 CAN frames in CANrawSender shall be presented in table view

src/common/datamodeltypes/candevicedata.h, src/components/candevice/candevicemodel.h, src/components/canrawsender/canrawsendermodel.h, src/components/canrawview/canrawviewmodel.h
=> CDS-69 Doxygen

src/common/cdswidget.h, src/components/canrawsender/canrawsender.cpp, src/components/canrawsender/crsgui.hpp, src/gui/mainwindow.cpp, src/gui/mainwindow.h
Fixed bug introduced by CDS-40
Fixed application close event
=> CDS-72 CANrawSender window causes crash

hooks/pre-commit, src/components/canrawsender/canrawsender_p.h, tests/candeviceqt_test.cpp, tests/candevicetest.cpp, tests/example.cpp
Added three additional CanDevice tests 
+ added optional pre-commit hook
=> CDS-26 CANdevice shall emit signal on reception of CAN frame. Emitted signal shall contain CAN frame.

.travis.sh, .travis.yml
CDS-65 subtask
Added new docker configuration to enable xvfb.
=> CDS-73  Unit Tests require display server

src/components/CMakeLists.txt, src/components/candevice/candevice.cpp, src/components/candevice/candevice.h, src/components/candevice/candevicemodel.cpp, src/components/candevice/candevicemodel.h, src/components/canrawview/canrawview.ui, src/components/projectconfiguration/CMakeLists.txt, src/components/projectconfiguration/flowviewwrapper.h, src/components/projectconfiguration/modeltoolbutton.h, src/components/projectconfiguration/projectconfiguration.cpp, src/components/projectconfiguration/projectconfiguration.h, src/components/projectconfiguration/projectconfiguration.ui, src/components/projectconfiguration/projectconfiguration_p.h, src/gui/CMakeLists.txt, src/gui/mainwindow.cpp, src/gui/mainwindow.h
Finished except for stop and start action passing to Project Configuration. For now actions are passed in constructor. I will continue work on better solution in CDS-86 task.
=> CDS-85 MainWindow refactoring, implementation

src/components/candevice/candevice.cpp, tests/candevicetest.cpp
=> CDS-93 Fixing CanDevice send queue handling

src/components/candevice/candevice.cpp, src/components/canrawview/canrawview_p.h, src/components/canrawview/gui/canrawview.ui, src/components/canrawview/uniquefiltermodel.cpp, src/components/canrawview/uniquefiltermodel.h
=> CDS-94 Fixing sorting in CanRawView

src/gui/mainwindow.cpp
=> CDS-95 Adding possibility to remove not existing projects from the recent list

.travis.sh, .travis.yml, src/components/CMakeLists.txt, src/components/canrawplayer/CMakeLists.txt, src/components/canrawplayer/canrawplayer.cpp, src/components/canrawplayer/canrawplayer.h, src/components/canrawplayer/canrawplayer_p.cpp, src/components/canrawplayer/canrawplayer_p.h, src/components/projectconfig/CMakeLists.txt, src/components/projectconfig/canrawplayermodel.cpp, src/components/projectconfig/canrawplayermodel.h, src/components/projectconfig/datamodeltypes/canrawplayerdata.h, src/components/projectconfig/dragwidget.cpp, src/components/projectconfig/nodepainter.h, src/components/projectconfig/projectconfig_p.h, src/gui/main.cpp, src/gui/mainwindow.cpp, tests/CMakeLists.txt, tests/canrawplayer_test.cpp, tests/canrawplayermodel_test.cpp, tools/templategen/main.cpp
CanRawPlayer added. Template generator updated with tests generation.
=> CanRawPlayer

src/gui/projectconfig/dragwidget.cpp
=> Fix for drag and drop issue reported as #122

files/css/darkStyle.css, src/components/canrawfilter/gui/canrawfilter.ui, src/components/canrawfilter/gui/canrawfilterguiimpl.h
Enhancement fixing misleading CanRawFilter interface reported in #121
=> CanRawFilter GUI enhancements

src/components/candevice/tests/candevice_test.cpp
Fix typos in candevice_test.cpp
=> Fix typos in candevice_test.cpp

.gitmodules, 3rdParty/CMakeLists.txt, src/common/componentmodel.h, src/common/tests/common_test.cpp, src/components/candevice/tests/candevice_test.cpp, src/components/candevice/tests/candevicemodel_test.cpp, src/components/canload/canload.cpp, src/components/canload/tests/canload_test.cpp, src/components/canload/tests/canloadmodel_test.cpp, src/components/canrawfilter/canrawfilter.cpp, src/components/canrawfilter/tests/canrawfilter_test.cpp, src/components/canrawfilter/tests/canrawfiltermodel_test.cpp, src/components/canrawlogger/canrawlogger.cpp, src/components/canrawlogger/tests/canrawlogger_test.cpp, src/components/canrawlogger/tests/canrawloggermodel_test.cpp, src/components/canrawplayer/canrawplayer.cpp, src/components/canrawplayer/tests/canrawplayer_test.cpp, src/components/canrawplayer/tests/canrawplayermodel_test.cpp, src/components/canrawsender/gui/nlmcheckbox.h, src/components/canrawsender/tests/canrawsender_test.cpp, src/components/canrawsender/tests/canrawsendermodel_test.cpp, src/components/canrawsender/tests/newlinemanager_test.cpp, src/components/canrawview/tests/canrawview_test.cpp, src/components/canrawview/tests/canrawviewmodel_test.cpp, src/gui/projectconfig/tests/projectconfig_test.cpp, src/gui/projectconfig/tests/projectconfig_test_noqrc.cpp, tools/templategen/main.cpp
- Bump fakeit up to v2.0.5
- Fix GCC 8 warning
- Fix Clang 7 warnings
=> Bump up fakeit

src/common/guiinterface/lineeditinterface.h, src/components/candevice/candevice_p.h, src/components/canrawsender/gui/nlmlineedit.h, src/components/canrawsender/newlinemanager.cpp, src/components/canrawsender/tests/canrawsender_test.cpp, src/components/canrawsender/tests/newlinemanager_test.cpp, src/components/canrawview/canrawview_p.h, src/components/canrawview/gui/crvgui.h, src/components/canrawview/tests/canrawview_test.cpp
Fix of Standard and Extended Frame Format handling as reported in #138 and #137.
=> Fix SFF and EFF handling

.appveyor.yml, .gitignore, .gitmodules, 3rdParty/CMakeLists.txt, CMakeLists.txt, codecov.yml, files/css/darkStyle.css, files/css/lightStyle.css, src/common/datamodeltypes/candbdata.h, src/components/cansignaldata/CMakeLists.txt, src/components/cansignaldata/cansignaldata.cpp, src/components/cansignaldata/cansignaldata.h, src/components/cansignaldata/cansignaldata_p.cpp, src/components/cansignaldata/cansignaldata_p.h, src/components/cansignaldata/cansignaldatamodel.cpp, src/components/cansignaldata/cansignaldatamodel.h, src/components/cansignaldata/cansignaldataplugin.h, src/components/cansignaldata/gui/cansignaldata.ui, src/components/cansignaldata/gui/cansignaldataguiimpl.h, src/components/cansignaldata/gui/cansignaldataguiint.h, src/components/cansignaldata/searchmodel.cpp, src/components/cansignaldata/searchmodel.h, src/components/cansignaldata/tests/cansignaldata_test.cpp, src/components/cansignaldata/tests/cansignaldatamodel_test.cpp, src/components/cansignaldata/tests/dbc/project.cds, src/components/cansignaldata/tests/dbc/tesla_can.dbc, src/components/cansignaldata/tests/tesla_can.dbc, tools/templategen/main.cpp, travis/before_install.sh, travis/docker_compile.sh
Poriting of CanSignalData (#144) to master completed.
=> CanSignalData

tools/templategen/CMakeLists.txt, tools/templategen/main.cpp, travis/docker_compile.sh
Fixed compile error when try add component. OS ubuntu 16.04.
Signed-off-by: Czesław Zagórski <czeslaw.zagorski@mobica.com>
=> Fixed compile error for old boost version and old cmake.

src/components/cansignaldecoder/CMakeLists.txt, src/components/cansignaldecoder/cansignaldecoder.cpp, src/components/cansignaldecoder/cansignaldecoder.h, src/components/cansignaldecoder/cansignaldecoder_p.cpp, src/components/cansignaldecoder/cansignaldecoder_p.h, src/components/cansignaldecoder/cansignaldecodermodel.cpp, src/components/cansignaldecoder/cansignaldecodermodel.h, src/components/cansignaldecoder/cansignaldecoderplugin.h, src/components/cansignaldecoder/tests/cansignaldecoder_test.cpp, src/components/cansignaldecoder/tests/cansignaldecodermodel_test.cpp, src/components/cansignaldecoder/tests/dbc/tesla_can.dbc, src/components/cansignalsender/gui/cansignalsenderguiimpl.h
=> CanSignalDecoder

files/css/lightStyle.css, src/components/canrawsender/canrawsender_p.cpp, src/components/canrawsender/canrawsender_p.h, src/components/canrawsender/newlinemanager.cpp, src/components/canrawsender/newlinemanager.h, src/components/canrawsender/tests/canrawsender_test.cpp, src/components/canrawsender/tests/configfiles/canrawsenderconfig.cds, src/components/canrawsender/tests/configfiles/canrawsenderconfig_badData.cds, src/components/canrawsender/tests/configfiles/canrawsenderconfig_badId.cds, src/components/canrawsender/tests/configfiles/canrawsenderconfig_badInterval.cds, src/components/canrawsender/tests/configfiles/canrawsenderconfig_badcolumns.cds, src/components/canrawsender/tests/newlinemanager_test.cpp, src/components/canrawview/canrawview_p.h, src/components/canrawview/tests/canrawview_test.cpp
#152 [Feature Request] Add support for sending and receiving CAN Remote frames
=> Added support for CAN Remote frames

.github/workflows/build.yml, CMakeLists.txt
Qt5Qml.dll
Qt5QmlModels.dll
Qt5Quick.dll
Qt5QuickWidgets.dll
=> Fix missing Qt5 DLLs in Windows Standalone build
